会場を株式会社インプレスに変更
ARkE1SM/ichiyasaGitSample pull request #1
Opened 2022-08-07 13:29 UTC by ARkE1SM

## 変更内容
イベント会場を「株式会社インプレス」に更新しました

## 背景
「株式会社インプレス」さんがイベント会場を提供してくださることになりました。

2022-08-07 14:11 UTC, kasamaxia-zero commented
修正ありがとうございました！問題ないのでマージします！

2022-08-08 08:13 UTC, kasamaxia-zero commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
正式名称で表記してくれてありがとうございます。

2022-08-08 08:15 UTC, ARkE1SM commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
マージしても良いですか？

2022-08-08 08:18 UTC, kasamaxia-zero requested changes
再度確認をお願いします。

2022-08-08 08:23 UTC, ARkE1SM reviewed
確認が完了しました。

2022-08-08 08:23 UTC, ARkE1SM commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
正式表記はこれで問題ありません。

2022-08-08 08:25 UTC, kasamaxia-zero commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
ありがとうございます！

2022-08-08 08:26 UTC, kasamaxia-zero commented
この内容でマージします。

2022-08-08 08:29 UTC, kasamaxia-zero approved these changes
この内容でマージしてください。

2022-08-08 10:02 UTC, kasamaxia-zero requested changes

2022-08-08 10:02 UTC, kasamaxia-zero commented on index.html
> +                        <p>株式会社インプレス イベントセミナー会場</p>
取り消します。

2022-08-08 10:07 UTC, kasamaxia-zero approved these changes

2022-08-09 07:38 UTC, merged